// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	"github.com/aql-lang/aql/eng"
	sdk "github.com/voxgig-sdk/art-institute-of-chicago-sdk/go"
)

// registerSDKWords installs three native AQL words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word.
func registerSDKWords(r *eng.Registry, client *sdk.ArtInstituteOfChicagoSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.NativeSig{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		dual := eng.NativeSig{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Handler: func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			},
			Returns: []*eng.Type{eng.TAny},
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:        op,
			ForwardArgs: true,
			Signatures:  []eng.NativeSig{single, dual},
		})
	}
}

func runOp(client *sdk.ArtInstituteOfChicagoSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.ArtInstituteOfChicagoSDK, name string) (sdk.ArtInstituteOfChicagoEntity, error) {
	switch strings.ToLower(name) {
	case "agent":
		return client.Agent(nil), nil
	case "agent_role":
		return client.AgentRole(nil), nil
	case "agent_type":
		return client.AgentType(nil), nil
	case "article":
		return client.Article(nil), nil
	case "artwork":
		return client.Artwork(nil), nil
	case "artwork_date_qualifier":
		return client.ArtworkDateQualifier(nil), nil
	case "artwork_place_qualifier":
		return client.ArtworkPlaceQualifier(nil), nil
	case "artwork_type":
		return client.ArtworkType(nil), nil
	case "category_term":
		return client.CategoryTerm(nil), nil
	case "digital_publication":
		return client.DigitalPublication(nil), nil
	case "digital_publication_article":
		return client.DigitalPublicationArticle(nil), nil
	case "educator_resource":
		return client.EducatorResource(nil), nil
	case "event":
		return client.Event(nil), nil
	case "event_occurrence":
		return client.EventOccurrence(nil), nil
	case "event_program":
		return client.EventProgram(nil), nil
	case "exhibition":
		return client.Exhibition(nil), nil
	case "gallery":
		return client.Gallery(nil), nil
	case "generic_page":
		return client.GenericPage(nil), nil
	case "highlight":
		return client.Highlight(nil), nil
	case "hour":
		return client.Hour(nil), nil
	case "image":
		return client.Image(nil), nil
	case "landing_page":
		return client.LandingPage(nil), nil
	case "place":
		return client.Place(nil), nil
	case "press_release":
		return client.PressRelease(nil), nil
	case "printed_publication":
		return client.PrintedPublication(nil), nil
	case "product":
		return client.Product(nil), nil
	case "publication":
		return client.Publication(nil), nil
	case "search":
		return client.Search(nil), nil
	case "section":
		return client.Section(nil), nil
	case "site":
		return client.Site(nil), nil
	case "sound":
		return client.Sound(nil), nil
	case "static_page":
		return client.StaticPage(nil), nil
	case "text":
		return client.Text(nil), nil
	case "tour":
		return client.Tour(nil), nil
	case "video":
		return client.Video(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts an AQL Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.VType.Matches(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.VType.Matches(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.VType)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
