<?php
declare(strict_types=1);

// ArtInstituteOfChicago SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

ArtInstituteOfChicagoUtility::setRegistrar(function (ArtInstituteOfChicagoUtility $u): void {
    $u->clean = [ArtInstituteOfChicagoClean::class, 'call'];
    $u->done = [ArtInstituteOfChicagoDone::class, 'call'];
    $u->make_error = [ArtInstituteOfChicagoMakeError::class, 'call'];
    $u->feature_add = [ArtInstituteOfChicagoFeatureAdd::class, 'call'];
    $u->feature_hook = [ArtInstituteOfChicagoFeatureHook::class, 'call'];
    $u->feature_init = [ArtInstituteOfChicagoFeatureInit::class, 'call'];
    $u->fetcher = [ArtInstituteOfChicagoFetcher::class, 'call'];
    $u->make_fetch_def = [ArtInstituteOfChicagoMakeFetchDef::class, 'call'];
    $u->make_context = [ArtInstituteOfChicagoMakeContext::class, 'call'];
    $u->make_options = [ArtInstituteOfChicagoMakeOptions::class, 'call'];
    $u->make_request = [ArtInstituteOfChicagoMakeRequest::class, 'call'];
    $u->make_response = [ArtInstituteOfChicagoMakeResponse::class, 'call'];
    $u->make_result = [ArtInstituteOfChicagoMakeResult::class, 'call'];
    $u->make_point = [ArtInstituteOfChicagoMakePoint::class, 'call'];
    $u->make_spec = [ArtInstituteOfChicagoMakeSpec::class, 'call'];
    $u->make_url = [ArtInstituteOfChicagoMakeUrl::class, 'call'];
    $u->param = [ArtInstituteOfChicagoParam::class, 'call'];
    $u->prepare_auth = [ArtInstituteOfChicagoPrepareAuth::class, 'call'];
    $u->prepare_body = [ArtInstituteOfChicagoPrepareBody::class, 'call'];
    $u->prepare_headers = [ArtInstituteOfChicagoPrepareHeaders::class, 'call'];
    $u->prepare_method = [ArtInstituteOfChicagoPrepareMethod::class, 'call'];
    $u->prepare_params = [ArtInstituteOfChicagoPrepareParams::class, 'call'];
    $u->prepare_path = [ArtInstituteOfChicagoPreparePath::class, 'call'];
    $u->prepare_query = [ArtInstituteOfChicagoPrepareQuery::class, 'call'];
    $u->graphql_body = [ArtInstituteOfChicagoGraphql::class, 'body'];
    $u->graphql_errors = [ArtInstituteOfChicagoGraphql::class, 'errors'];
    $u->result_basic = [ArtInstituteOfChicagoResultBasic::class, 'call'];
    $u->result_body = [ArtInstituteOfChicagoResultBody::class, 'call'];
    $u->result_headers = [ArtInstituteOfChicagoResultHeaders::class, 'call'];
    $u->transform_request = [ArtInstituteOfChicagoTransformRequest::class, 'call'];
    $u->transform_response = [ArtInstituteOfChicagoTransformResponse::class, 'call'];
});
